### ISSUE TITLE
[BUG] Can't see my bought cores on Rococo

### ISSUE THREAD

**Issue by the-right-joyce** [LasticXYZ/LasticUI#174] opened 2024-05-06 13:19 UTC
**Describe the bug**
Can't see my bought cores on UI.

**To Reproduce**

 Go to Marketplace > The sales info here is also static, didn't change after I bought a core neither
 
<img width="850" alt="image" src="https://github.com/LasticXYZ/LasticUI/assets/98593770/6b013f56-cee1-430d-ba70-4cb0c2a12d1d">

Click on buy core > Purchase successful > Go to "My Cores" > Core not shown
<img width="1314" alt="image" src="https://github.com/LasticXYZ/LasticUI/assets/98593770/aed9ab2b-0a02-4fe5-afa0-741fa2d81b9f">

The purchase was successful, as seen here: https://coretime-rococo.subscan.io/extrinsic/1428439-2
Also before that I had bought a core on RegionX and I could not see my core on Lastic: https://coretime-rococo.subscan.io/extrinsic/1427687-2
But on RegionX I could see both cores bought. 
<img width="886" alt="image" src="https://github.com/LasticXYZ/LasticUI/assets/98593770/e1164062-87e8-451f-8373-d0d7b0508b75">

It's just a rococo bug, so it's not critical, but I wanted to test the UI and couldn't since my cores are not shown.

- OS: macOS Sonoma 14.4.1
- Browser: Arc, Chromium Engine Version 124.0.6367.79

**Comment by poppyseedDev** [comment] 2024-06-09 11:52
This issue was resolved with the update of the subsquid repository: https://github.com/LasticXYZ/subsquid/pull/13
3 weeks ago, the issue is that the metadata changes a lot on Rococo (this is not such an issue on Kusama) and the core purchases are not being fetched from the state but from the indexer. And the indexer kept crashing with every metadata change, it is now handled in such a way that immediate crashes are prevented, but we are monitoring it closely.

**Closed by poppyseedDev** 2024-06-09 11:52 UTC
Labels: bug
